[alias]
xtask = "run -p xtask --"

[target.x86_64-unknown-none]
rustflags = [
  "-C",
  "link-arg=-Tkernel/kernel.ld",
  "-C",
  "relocation-model=static",
  "-C",
  "relro-level=off",
  "-C",
  "panic=abort",
]
